### ISSUE TITLE
Abricate vs AMRPlusPlus2.0

### ISSUE THREAD

**Issue by AroArz** [Jtrachsel/megares_db_4_abricate#1]
Hi!

I apologise if this questions is a bit naive.

I'm wondering what the benefit is to incorporate this database into ABRicate in contrast to using MEGARES2.0 own tool AMRPlusPlus2.0? As you mentioned some resistance genes which require SNP confirmation have been removed in this database whilst AMRPlusPlus2.0 utilises Resistance Gene Identifier (RGI) for automated in silico confirmation of those SNPs, which might be relevant. 
Aside from this, have you experienced any other difficulties running MEGARES2.0 db on ABRicate?

I've previously used Abricate and I'm currently reviewing if it is still the most suitable tool for me to use.

**Comment by Jtrachsel** [comment]
Hello!

Honestly I was not aware of the AMRPlusPlus2.0 tool.  I like abricate because it's fast, easy to use, and is relatively quick to install.  In looking at the AMRPlusPlus2.0 tool it looks like it has a good number of dependencies and might be a bit more work to get configured correctly.  

I use abricate as part of a pipeline I'm working on and I want to keep the dependencies to a minimum so that it's more portable.  Additionally, the projects I am working on are mostly concerned with AMR genes that are transferable, so the SNP based ones are of secondary importance to me right now.  Another point in favor of abricate is that you can screen for virulence genes, plasmid typing genes etc in parallel to an AMR search.   It's also pretty easy to make custom abricate databases (like this one!)

If you want an exhaustive analysis of all potential AMR phenotypes AMRPlusPlus2.0 might be a better option than abricate, but if you just want an easy to execute, very fast overview of genes of interest in your assembled data it's hard to beat abricate.

I like the MEGARes2.0 database because made the BacMet biocide and metal resistance database available in nucleotide format.  There are probably many ways to format the MEGARes2.0 database for use with abricate, the way I did it here has worked pretty well for me so far, but I've only used it in a few instances.  

Hope this helps, If you decide to try abricate with this database let me know if you come across any issues.

**Comment by AroArz** [comment]
Hey! 

Thanks for the reply and your reflections. Theres a fair chance I'll be using abricate on your version of  MEGARes2.0 in the coming weeks. I'll let you know how it goes. 

Cheers.
